apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-app
  template:
    metadata:
      labels:
        app: oficina-app
    spec:
      containers:
        - name: oficina-app
          image: ghcr.io/luscuissiatto/oficina-app:latest
          ports:
            - containerPort: 8080
          env:
            # Conexão com o Banco (RDS)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://oficina-db-instance.cwx8ygkc4hs8.us-east-1.rds.amazonaws.com:5432/oficina"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oficina-secret # <--- Vamos criar esse secret via GitHub Actions ou Terraform
                  key: DB_PASSWORD
            
            # Configuração do Token (Mesma da Lambda)
            - name: API_SECURITY_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: oficina-secret
                  key: JWT_SECRET

            - name: SPRING_MAIL_HOST
              value: "mailhog-service"  # Nome do serviço do MailHog no Kubernetes
            - name: SPRING_MAIL_PORT
              value: "1025"             # Porta SMTP do MailHog
            - name: SPRING_MAIL_USERNAME
              value: ""                 # MailHog não precisa de senha
            - name: SPRING_MAIL_PASSWORD
              value: ""
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "false"
            - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "false"