apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
type: Opaque
stringData:
  DB_PASSWORD: "SenhaTerraform9494"
  JWT_SECRET: "bWluaGEtY2hhdmUtc2VjcmV0YS1zdXBlci1zZWd1cmE="

# apiVersion: v1
# kind: Secret
# metadata:
#   name: oficina-secret
# type: Opaque
# data:
#   jwt-secret: bWluaGEtY2hhdmUtc2VjcmV0YS1qd3QtbXVpdG8tbG9uZ2E=
#   admin-password: cGFzc3dvcmQ=