name: Infra K8s Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy-infra-and-apps:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: 'us-east-1'

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
          
      - name: Configure Kubectl
        run: aws eks update-kubeconfig --name oficina-cluster-final --region us-east-1
        
      - name: Deploy K8s Manifests
        run: kubectl apply -f .